export default = [
  {
    "identifier": "1",
    "scientificName": "Cyperus difformis L.",
    "seedType": "elliptic",
    "plantType": "Sedge",
    "lowland": "✔",
    "upland": "",
    "commonName": "Variable flatsedge, Small flower umbrella plant",
    "khmerName": "",
    "familyName": "Cyperacee",
    "description": "Annual with fibrous and reddish roots; up to 100 cm tall. Stems are tufted, smooth and erect, triangular and 2−3 mm thick; slightly winged. Three to 4 basal leaves; sheaths united at base, lower ones straw-colored to brown; blades flaccid and linear, 15−45 cm long. Inflorescence is umbellate and subtended by two leaf-like bracts; rays 1−5 cm long, some with long peduncle, some without stalk; spikelets numerous, crowded in masses about 2−5 mm long, each spikelet composed of 10−30 flowers. Fruit is a brownish nut, elliptical to slightly obovate, about 0.6 mm long and lightly pitted.",
    "habitat": "The plant grows well in flooded or moist fertile soils and common in lowland rice. Also found on poorer sandy or clay soils in fallow lands but cannot tolerate deep flooding. It has a short life span; propagates by seeds and produces seeds throughout the year.",
    "controlMethods": "Hand and mechanical weeding. Pre-sowing and post-emergence herbicide e.g. 2,4-D. Pre-emergence herbicide e.g. Butachlor. http://www.knowledgebank.irri.org/training/fact-sheets/item/cyperus-difformis'",
    "herbicideResistance": "Has developed herbicide resisrance to ALS inhibitors (Group B2):  azimsulfuron, bensulfuron-methyl, bispyribac-sodium, and penoxsulam ",
    "reference": "http://www.knowledgebank.irri.org/training/fact-sheets/item/cyperus-difformis",
    "imageCopyright": "Prof Robert J. Martin\nASR/University of Sydney\nbobmartin@asrcambodia.com",
    "images": { seed: require('../images/plant-images/Cyperus_difformis/Cyperus_difformis_seed_1.JPG'), mature: require('../images/plant-images/Cyperus_difformis/Cyperus_difformis_mature_1.JPG'), flower: require('../images/plant-images/Cyperus_difformis/Cyperus_difformis_flower_1.JPG')}
  },
  {
    "identifier": "2",
    "scientificName": "Cyperus iria L.",
    "seedType": "elliptic, obovoid",
    "plantType": "Sedge",
    "lowland": "✔",
    "upland": "",
    "commonName": " Rice flat sedge",
    "khmerName": "",
    "familyName": "Cyperacee",
    "description": "Tufted annual herb, or occasionally perennial, with fibrous roots, 15−75 yellowish red roots; 10−70 cm tall. Stems are sharply 3 angled, tufted, smooth, 5−80 cm high. Leaves are basal, rough to touch in upper part, linear, flaccid, with gradually tapering point and 3−8 mm wide; sheath is reddish or purplish brown, enveloping the stem at base. Inflorescence is simple or compound umbel composed of numerous erect-spreading 3−10 mm long flattened spikelets. Fruit is a three-angled, 1.0−1.5 mm nut with slightly concave sides, and shiny dark brown to black.",
    "habitat": "Thrives in wetland rice, dryland annual crops, and plantation crops. Multiplies rapidly: can produce 3,000−5,000 seeds per plant, seedlings emerge immediately after rice is sown; flowers month later and can establish second generation in the same season. It flowers throughout the year.",
    "controlMethods": "Hand weeding at earlier stage of growth. Pre-emergence and post-emergence herbicides http://www.knowledgebank.irri.org/training/fact-sheets/item/cyperus-iria'",
    "herbicideResistance": "Has developed herbicide resisrance to ALS inhibitors (Group B2): pyrazosulfuron-ethyl and they may be cross-resistant to other Group B/2 herbicides.",
    "reference": "http://www.knowledgebank.irri.org/training/fact-sheets/item/cyperus-iria",
    "imageCopyright": "Prof Robert J. Martin\nASR/University of Sydney\nbobmartin@asrcambodia.com",
    "images": { seed: require('../images/plant-images/Cyperus_iria/Cyperus_iria_seed_1.JPG'), mature: require('../images/plant-images/Cyperus_iria/Cyperus_iria_mature_1.JPG'), flower: require('../images/plant-images/Cyperus_iria/Cyperus_iria_flower_1.JPG')}
  },
  {
    "identifier": "3",
    "scientificName": "Echinochloa colona (L.) Link",
    "seedType": "elliptic",
    "plantType": "Grass",
    "lowland": "✔",
    "upland": "✔",
    "commonName": "Awnless barnyard grass",
    "khmerName": "Smao bek kbal",
    "familyName": "Poaceae",
    "description": "A tufted annual grass, up to 60 cm tall. Stems are reddish purple or green, ascending to erect, without hairs. Leaf is linear, 10−15 cm long, basal portion often tinged with red or purple; ligule absent. Inflorescence is simple, ascending racemes, green to purple, about 5−15 cm long; spikelets subsessile 1−3 mm long.",
    "habitat": "Flowers throughout the year and is propagated by seeds. Seeds have a short dormancy period. It can be present in large numbers and responsive to nutrients. Prefers moist but unflooded conditions and is a problem mainly in upland and rainfed lowland rice fields rather than in flooded fields.",
    "controlMethods": "Flooding Hand weeding or use of hoe Pre-emergence & post-emergence herbicides application http://www.knowledgebank.irri.org/training/fact-sheets/item/echinochloa-colona'",
    "herbicideResistance": "Multiple resistance has evolved to herbicides in the Groups B/2, C2/7, and L/26.  These particular biotypes are known to have resistance to imazethapyr, propanil, and quinclorac (MOA in monocots) and they may be cross-resistant to other herbicides in the Groups B/2, C2/7, and L/26.",
    "reference": "http://www.knowledgebank.irri.org/training/fact-sheets/item/echinochloa-colona",
    "imageCopyright": "Prof Robert J. Martin\nASR/University of Sydney\nbobmartin@asrcambodia.com",
    "images": { seed: require('../images/plant-images/Echinochloa_colona/Echinochloa_colona_seed_1.JPG'), mature: require('../images/plant-images/Echinochloa_colona/Echinochloa_colona_mature_1.JPG'), flower: require('../images/plant-images/Echinochloa_colona/Echinochloa_colona_flower_1.JPG')}
  },
  {
    "identifier": "4",
    "scientificName": "Echinochloa crus galli (L.) Beauv.",
    "seedType": "elliptic",
    "plantType": "Grass",
    "lowland": "✔",
    "upland": "",
    "commonName": "Common barnyard grass",
    "khmerName": "",
    "familyName": "Poaceae",
    "description": "Annual, erect, tufted or reclining at base; up to 200 cm tall. Stem is rooting at lower nodes, cylindrical, without hairs, and filled with white spongy pith. Leaf is linear with a broad round base and narrow top; blade 10−40 cm long; ligule absent. Inflorescence is loose green to purplish, 10−25 cm long comprising compound racemes; spikelets are more or less elliptical and pointed, usually slightly hairy; awns, if present, green to purplish, 2−5 mm long.",
    "habitat": "Propagates by seed. Flowers throughout the year and can produce seeds within 60 days. Prefers moist to wet land; easily grows in direct-seeded rice fields and wastelands. It is a common weed in swamps and aquatic places. ",
    "controlMethods": "Thorough land preparation for rice under wet or dry conditions. The fungal pathogen, Exserohilum monoceras. Pre-emergence & post-emergence herbicide http://www.knowledgebank.irri.org/training/fact-sheets/item/echinochloa-crus-galli'",
    "herbicideResistance": "Research has shown resistance to imazapyr, imazethapyr, and pyrazosulfuron-ethyl and they may be cross-resistant to other Group B/2 herbicides.",
    "reference": "http://www.knowledgebank.irri.org/training/fact-sheets/item/echinochloa-crus-galli",
    "imageCopyright": "Prof Robert J. Martin\nASR/University of Sydney\nbobmartin@asrcambodia.com",
    "images": { seed: require('../images/plant-images/Echinochloa_crus/Echinochloa_crus_seed_1.JPG'), mature: require('../images/plant-images/Echinochloa_crus/Echinochloa_crus_mature_1.JPG'), flower: require('../images/plant-images/Echinochloa_crus/Echinochloa_crus_flower_1.JPG')}
  },
  {
    "identifier": "5",
    "scientificName": "Fimbristylis miliacea (L.) Vahl",
    "seedType": "obovoid",
    "plantType": "Sedge",
    "lowland": "✔",
    "upland": "",
    "commonName": "Lesser fimbrystylis",
    "khmerName": "",
    "familyName": "Cyperacee",
    "description": "Annual or perennial, without hairs, strongly tillering, with fibrous roots and up to 80−90 cm high. Stem: slender, erect, densely tufted, compressed, and smooth; strongly angled at the top and flattened at the base; 20−70 cm tall. Leaf: stiff and thread-like; on flowerless stems: in 2 rows and with flattened sheaths; no prominent midribs; on flowering stems: only linear leaf sheaths; basal leaves have overlapping leaf sheaths; ligule absent. Inflorescence: 6−10 cm long, compound umbel with 6−50 spikelets; spikelets reddish brown, 2−4 mm long and either round or acute at apex. Fruit: straw-colored or pale ivory nut, 0.2−0.3 mm long.",
    "habitat": "Propagates by seeds; flowers year-round and produces 10,000 seeds per plant; seeds can germinate immediately after reaching maturity. In rice fields, seedlings appear soon after rice is sown; flowers in about one month and capable of producing a second generation in the same season. Germinates where flood water is shallow or absent and seedlings may emerge throughout the entire growing period of rice.",
    "controlMethods": "Hand cultivation Post-emergence herbicide e.g. 2,4-D http://www.knowledgebank.irri.org/training/fact-sheets/item/fimbristylis-miliacea'",
    "herbicideResistance": "imazapyr, imazethapyr, and pyrazosulfuron-ethyl and may be cross-resistant to other Group B/2 herbicides.",
    "reference": "http://www.knowledgebank.irri.org/training/fact-sheets/item/fimbristylis-miliacea",
    "imageCopyright": "Prof Robert J. Martin\nASR/University of Sydney\nbobmartin@asrcambodia.com",
    "images": { seed: require('../images/plant-images/Fimbristylis_miliacea/Fimbristylis_miliacea_seed_1.JPG'), mature: require('../images/plant-images/Fimbristylis_miliacea/Fimbristylis_miliacea_mature_1.JPG'), flower: require('../images/plant-images/Fimbristylis_miliacea/Fimbristylis_miliacea_flower_1.JPG')}
  },
  {
    "identifier": "6",
    "scientificName": "Ischaemum rugosum Salisb.",
    "seedType": "ovoid",
    "plantType": "Grass",
    "lowland": "✔",
    "upland": "",
    "commonName": "Wrinkle duck beak",
    "khmerName": "Smao srauv",
    "familyName": "Poaceae",
    "description": "An erect or ascending annual or perennial; up to 100 cm tall. Stem: often purplish, usually has hairs at nodes, cylindrical. Leaf: blades 10−30 cm long, glabrous or with scattered hairs on both surfaces; compressed sheaths rather loose and green or purplish, with hairs on margins; ligule: membranous and fused with auricles. Inflorescence: paired terminal spikes that are often strongly pressed against one another, thus appearing like a single spike. At maturity, it separates into two spike-like racemes. Spikelets: paired, one is sessile, the other pedicelled; sessile spikelet yellowish green, up to 6 mm long, first glume prominently transversely wrinkled; awns are spiral at base, dark colored. ",
    "habitat": "Propagates by seeds. Seeds do not germinate while submerged though, after emergence, they can grow easily under flooded conditions. Ischaemum rugosum is found in wet conditions, especially in direct-seeded rice fields.",
    "controlMethods": "Hand weeding or hoeing. Pre-emergence herbicide application e.g. Butachlor or pendimethalin http://www.knowledgebank.irri.org/training/fact-sheets/item/ischaemum-rugosum-salisb'",
    "herbicideResistance": "Paraquat and may be cross-resistant to other Group D/22 herbicides.",
    "reference": "http://www.knowledgebank.irri.org/training/fact-sheets/item/ischaemum-rugosum-salisb",
    "imageCopyright": "Prof Robert J. Martin\nASR/University of Sydney\nbobmartin@asrcambodia.com",
    "images": { seed: require('../images/plant-images/Ischaemum_rugosum/Ischaemum_rugosum_seed_1.JPG'), mature: require('../images/plant-images/Ischaemum_rugosum/Ischaemum_rugosum_mature_1.JPG'), flower: require('../images/plant-images/Ischaemum_rugosum/Ischaemum_rugosum_flower_1.JPG')}
  },
  {
    "identifier": "7",
    "scientificName": "Leptochloa chinensis (L.) Nees",
    "seedType": "elliptic",
    "plantType": "Grass",
    "lowland": "✔",
    "upland": "",
    "commonName": "Chinese sprangletop",
    "khmerName": "",
    "familyName": "Poaceae",
    "description": "A tufted and smooth annual or perennial; up to 120 cm tall. Stem: slender, hollow, erect or ascending from a branching base, rooting at lower nodes, smooth and without hair, typically 10−20 nodes, and can reach as high as 50−100 cm. Leaf: smooth, linear, 10−30 cm long; ligule an inconspicuous membrane 1−2 mm long and deeply divided into hairlike segments. Inflorescence: narrowly ovate, loose panicle, main axis 10−40 cm long, and with many spike-like slender branches; racemes slender, each with two rows of spikelets, spikelets 2−3.2 mm long, purplish or green and 4−6 flowered.",
    "habitat": "Red sprangletop propagates by seeds or vegetatively by rootstocks. Germination does not occur when seeds are submerged in water.\n\n",
    "controlMethods": "The use of crop seed free from wild rice, crop rotation, soil puddling, hand weeding of initial infestations, and water management. Pre-sowing herbicide application. http://www.knowledgebank.irri.org/training/fact-sheets/item/oryza-sativa'",
    "herbicideResistance": "Cyhalofop-butyl and  may be cross-resistant to other Group A/1 herbicides.",
    "reference": "http://www.knowledgebank.irri.org/training/fact-sheets/item/leptochloa-chinensis",
    "imageCopyright": "Prof Robert J. Martin\nASR/University of Sydney\nbobmartin@asrcambodia.com",
    "images": { seed: require('../images/plant-images/Leptochloa_chinensis/Leptochloa_chinensis_seed_1.JPG'), mature: require('../images/plant-images/Leptochloa_chinensis/Leptochloa_chinensis_mature_1.JPG'), flower: require('../images/plant-images/Leptochloa_chinensis/Leptochloa_chinensis_flower_1.JPG')}
  },
  {
    "identifier": "8",
    "scientificName": "Ipomoea aquatica Forssk.",
    "seedType": "triquetrous",
    "plantType": "Broadleaf",
    "lowland": "✔",
    "upland": "",
    "commonName": "Swamp morning glory",
    "khmerName": "Trakoeun",
    "familyName": "Convolvulaceae",
    "description": "I. aquatica is a sprawling vine, annual or perennial, creeping on mud or floating on water; stems terete, branched, hollow and succulent when floating, otherwise solid and firm, up to 3 m long, to 1 cm in diameter.",
    "habitat": "I. aquatica occurs in moist, marshy, or inundated localities, in shallow pools, ditches, or wet ricefields, from sea level to 1000 m. It forms dense masses and is easily propagated from cuttings. It is also cultivated as a vegetable in different parts of Asia.",
    "controlMethods": "TRotovating & puddling; Hand weeding during early stage Pre-emergence herbicide e.g. pendimethalin Post-emergence herbicide e.g. quinclorac http://www.knowledgebank.irri.org/training/fact-sheets/item/leptochloa-chinensis'",
    "herbicideResistance": "Not confirmed",
    "reference": "http://www.cabi.org/isc/datasheet/28781",
    "imageCopyright": "Prof Robert J. Martin\nASR/University of Sydney\nbobmartin@asrcambodia.com",
    "images": { mature: require('../images/plant-images/Ipomoea_aquatica/Ipomoea_aquatica_mature_1.JPG'), flower: require('../images/plant-images/Ipomoea_aquatica/Ipomoea_aquatica_flower_1.JPG')}
  },
  {
    "identifier": "9",
    "scientificName": "Oryza sativa f. spontanea Roshev.",
    "seedType": "cylindric",
    "plantType": "Grass",
    "lowland": "✔",
    "upland": "",
    "commonName": "Weedy rice",
    "khmerName": "Srangae, Muk chgai",
    "familyName": "Poaceae",
    "description": "A variable, erect, stout or slender annual rice with varying height and form. Stem: tufted, erect, hollow and slender or stout, smooth and hairless, 80−120 cm tall. Leaf: blade flat with parallel veins, 15−30 cm long; ligule and auricle present; ligule is usually 10−20 mm long. Inflorescence: an erect or nodding loose panicle, spikelet about 7 mm long, flat, one-flowered, with or without awns of varying length.",
    "habitat": "Weedy rice is highly variable and thought to originate from outcrosses to wild species (O. nivara, O. rufipogon) or as a result of outcrossing within domestic rice. It is distinguished by the key weedy traits of ready panicle shattering and variable secondary dormancy. It is highly adapted to a wide range of environmental conditions, dry land to deepwater culture. It commonly possesses red pericarp, which requires additional milling, thereby reducing the quality of milled rice.",
    "controlMethods": "Pre-sowing herbicide application e.g. Glyshopate Post-emergence herbicide application e.g. Quinclorac http://www.cabi.org/isc/datasheet/38670'",
    "herbicideResistance": "",
    "reference": "http://www.knowledgebank.irri.org/training/fact-sheets/item/oryza-sativa",
    "imageCopyright": "Prof Robert J. Martin\nASR/University of Sydney\nbobmartin@asrcambodia.com",
    "images": { seed: require('../images/plant-images/Oryza_sativa/Oryza_sativa_seed_1.JPG'), mature: require('../images/plant-images/Oryza_sativa/Oryza_sativa_mature_1.JPG'), flower: require('../images/plant-images/Oryza_sativa/Oryza_sativa_flower_1.JPG')}
  },
  {
    "identifier": "10",
    "scientificName": "Panicum repens L.",
    "seedType": "elliptic",
    "plantType": "Grass",
    "lowland": "✔",
    "upland": "",
    "commonName": "Torpedo grass",
    "khmerName": "",
    "familyName": "Poaceae",
    "description": "Perennial. Elongated rhizomes. Stolons absent, or present. Culms erect, or geniculately ascending; 30–100 cm long. Leaves are distichous. Ligule is a ciliate membrane. Leaf-blades erect; flat, or convolute; 7–25 cm long; 2–8 mm wide; coriaceous; stiff; glaucous. Leaf-blade apex acuminate, or attenuate; muticous, or pungent.",
    "habitat": "Natural habitats are often sandy, but it is able to persist in heavy soils that remain moist due to high rainfall, poor drainage or irrigation.\n\n",
    "controlMethods": "Hand weeding; (For culinary use as vegetable)'",
    "herbicideResistance": "",
    "reference": "http://www.cabi.org/isc/datasheet/38670",
    "imageCopyright": "Prof Robert J. Martin\nASR/University of Sydney\nbobmartin@asrcambodia.com",
    "images": { seed: require('../images/plant-images/Panicum_repens/Panicum_repens_seed_1.JPG'), mature: require('../images/plant-images/Panicum_repens/Panicum_repens_mature_1.JPG'), flower: require('../images/plant-images/Panicum_repens/Panicum_repens_flower_1.JPG')}
  },
  {
    "identifier": "11",
    "scientificName": "Melochia corchorifolia L.",
    "seedType": "triquetrous",
    "plantType": "Broadleaf",
    "lowland": "✔",
    "upland": "",
    "commonName": "Wire bush, Redweed",
    "khmerName": "Krachib",
    "familyName": "Malvaceae",
    "description": "Erect or spreading, branched, up to 130—cm—high, perennial or annual herb.\nStem: cylindrical with tough stringy bark and with scattered star-like hairs.\nLeaf: simple, with 2—3—cm petiole, alternately arranged; blades oblong to ovate, 3—8—cm—long with saw-toothed margins.\nInflorescence: terminal head or borne on leaf axils; flowers crowded and intermixed with linear bracteoles; petals white, pink, or pale purple, obovate, about 7—mm—long.\nFruit: depressed globose capsule, 4—5—mm in diameter with slightly beard-like hairs.\nSeed: grayish brown with black spots, obovoid, about 2.5—mm—long. ",
    "habitat": "Weed of dryland field crops, dry-seeded lowland rice, and some plantation crops. Flowers year-round; propagates by seed.",
    "controlMethods": "Cultural control: hand weeding or hoeing during the seedling stage to remove the weed.\nChemical control: postemergence herbicideapplication of MCPA or 2,4-D. ",
    "herbicideResistance": "",
    "reference": "http://keyserver.lucidcentral.org/key-server/data/08050103-0a0e-4e01-8a03-040d0c020e0a/media/Html/Melochia_corchorifolia.htm",
    "imageCopyright": "",
    "images": { seed: require('../images/plant-images/Melochia_corchorifolia/Melochia_corchorifolia_seed_1.JPG'), mature: require('../images/plant-images/Melochia_corchorifolia/Melochia_corchorifolia_mature_1.JPG'), flower: require('../images/plant-images/Melochia_corchorifolia/Melochia_corchorifolia_flower_2.JPG')}
  },
  {
    "identifier": "12",
    "scientificName": "Ludwigia octovalvis  (Jacq.) Raven",
    "seedType": "elliptic",
    "plantType": "Broadleaf",
    "lowland": "✔",
    "upland": "",
    "commonName": "Water primrose, primrose-willow",
    "khmerName": "",
    "familyName": "Onagraceae ",
    "description": "An erect, much-branched, robust perennial herb up to 150—cm—high.\nStem: erect, hairless, sparsely or densely hairy, sometimes woody at base, red-brown and lignified at base.\nLeaf: simple, arranged alternately along the stem; blade lance-shaped to ovate, 2.5—15—cm—long, light green and may turn red as plants age.\nInflorescence: flower solitary, axillary, without stalk; petals 4, yellow, broadly ovate or wedge-shaped, 1—1.5—cm—long.\nFruit: green or purplish at maturity capsule, cylindrical to somewhat club-shaped; 3—5—cm—long and 2—8—mm—wide with 8 ribs; fruits contain several rows of seeds.\nSeed: brown, rounded, beaked, and about 0.7—mm in diameter.",
    "habitat": "Adapted to a wide range of environments, including wet places, marshes, fresh-water lakes, streams, ditch banks, along railroads, on gravelly riverbeds, flood banks, paddy rice, and flooded grasslands.\nPropagates by seeds and a single plant can produce as many as 375,000 seeds; flowers year-round. ",
    "controlMethods": "Cultural control: hand weeding is effective.\nChemical control: postemergence herbicide application of 2,4-D and MCPA in rice",
    "herbicideResistance": "",
    "reference": "http://keyserver.lucidcentral.org/key-server/data/08050103-0a0e-4e01-8a03-040d0c020e0a/media/Html/Ludwigia_octovalvis.htm",
    "imageCopyright": "",
    "images": { seed: require('../images/plant-images/Ludwigia_octovalvis/Ludwigia_octovalvis_seed_1.JPG'), mature: require('../images/plant-images/Ludwigia_octovalvis/Ludwigia_octovalvis_mature_1.JPG')}
  },
  {
    "identifier": "13",
    "scientificName": "Cyanotis axillaris  (L.) D. Don ex Sweet",
    "seedType": "trapezoidal/deltoid",
    "plantType": "Broadleaf",
    "lowland": "✔",
    "upland": "✔",
    "commonName": "",
    "khmerName": "Champus tea",
    "familyName": "Commelinaceae",
    "description": "A branched prostrate or sub-erect, fleshy annual, rooting at the nodes.\nStem: round, pinkish, and procumbent; about 5 mm—thick, 20—40—cm—long.\nLeaf: lanceolate or linear, 4—11—cm—long and 0.6—1.2—cm—wide, glabrous upper surface; sheathing at the base, clasping the stem, and ciliate with long hairs on margins.\nInflorescence: purple or blue flowers in axillary clusters, partly hidden by the leaf sheaths; petals 3 and long with claws being united into a tube.\nFruit: capsule, beaked at the top.\nSeed: grayish and pitted, 2 in each cell, truncate at base with a small conical point at the top.",
    "habitat": "Cyanotis axillaris is found in paddy and damp places. It can reproduce vegetatively and by seeds",
    "controlMethods": "Cultural control: uproot plants and bury them; ensure clean seed or seedlings.",
    "herbicideResistance": "",
    "reference": "http://keyserver.lucidcentral.org/key-server/data/08050103-0a0e-4e01-8a03-040d0c020e0a/media/Html/Cyanotis_axillaris.htm",
    "imageCopyright": "",
    "images": { seed: require('../images/plant-images/Cyanotis_axillaris/Cyanotis_axillaris_seed_1.JPG'), mature: require('../images/plant-images/Cyanotis_axillaris/Cyanotis_axillaris_mature_1.JPG'), flower: require('../images/plant-images/Cyanotis_axillaris/Cyanotis_axillaris_flower_2.JPG')}
  },
  {
    "identifier": "14",
    "scientificName": "Aeschynomene indica L.",
    "seedType": "Reniform",
    "plantType": "Broadleaf",
    "lowland": "✔",
    "upland": "",
    "commonName": "Indian jointvetch",
    "khmerName": "",
    "familyName": "Fabaceae",
    "description": "An erect, branched, 0.3—1.2—m—tall, perennial herb or sub-shrub.\nStem: woody, with \"wart-like\" structures at the base, cylindrical with scattered glandular hairs.\nLeaf: alternate, pinnate, 3—8—cm—long; leaflets linear or oblong, about 2.5—10—mm—long; stipules are lance-shaped and 1—cm—long.\nInflorescence: racemes borne in leaf axils with 1—4 flowers: flower yellow and often suffused with purple, up to 10—mm—long.\nFruit: a linear-oblong, either straight or curved pod up to 5—cm—long and 4—mm—wide; seeds black, shiny, and about 3—3.5—mm—long. ",
    "habitat": "Favors wet situations, in direct-seeded rice and along margins of ditches. Seed has a pronounced dormancy; germination favored by saturated soil conditions.",
    "controlMethods": "Cultural control: in rice, hand weeding and interrow cultivation in India and Indonesia; in soybean, hand weeding at 20, 35, and 50 days after sowing.\nChemical control: thiobencarb and pendimethalin reported to be effective in direct-sown rice.",
    "herbicideResistance": "",
    "reference": "http://keyserver.lucidcentral.org/key-server/data/08050103-0a0e-4e01-8a03-040d0c020e0a/media/Html/Aeschynomene_indica.htm",
    "imageCopyright": "",
    "images": { seed: require('../images/plant-images/Aeschynomene_indica/Aeschynomene_indica_seed_1.JPG'), mature: require('../images/plant-images/Aeschynomene_indica/Aeschynomene_indica_mature_2.JPG'), flower: require('../images/plant-images/Aeschynomene_indica/Aeschynomene_indica_flower_2.JPG'), fruit: require('../images/plant-images/Aeschynomene_indica/Aeschynomene_indica_fruit_2.JPG')}
  },
  {
    "identifier": "15",
    "scientificName": "Aeschynomene aspera L.",
    "seedType": "Reniform",
    "plantType": "Broadleaf",
    "lowland": "✔",
    "upland": "        ",
    "commonName": "Sola pith plant",
    "khmerName": "",
    "familyName": "Fabaceae",
    "description": "An erect or ascending annual herb.\nStem: sparingly branched, without hairs, often woody at the base, and 100—200—cm—tall.\nLeaf: with 30—55 pinnately arranged leaflets; leaflet 5—21—mm—long, without hair on both sides.\nInflorescence: a 2—6—flowered raceme; both the standard and brown keel are densely hairy.\nFruit: hairless pod, 30—90—mm—long, 7—9—mm—wide, with 2—9 joints.",
    "habitat": "Common in swampy and open localities. ",
    "controlMethods": "No specific reports available on control of this weed.",
    "herbicideResistance": "",
    "reference": "http://keyserver.lucidcentral.org/key-server/data/08050103-0a0e-4e01-8a03-040d0c020e0a/media/Html/Aeschynomene_aspera.htm",
    "imageCopyright": "",
    "images": { seed: require('../images/plant-images/Aeschynomene_aspera/Aeschynomene_aspera_seed_3.JPG'), mature: require('../images/plant-images/Aeschynomene_aspera/Aeschynomene_aspera_mature_2.JPG'), flower: require('../images/plant-images/Aeschynomene_aspera/Aeschynomene_aspera_flower_1.JPG'), fruit: require('../images/plant-images/Aeschynomene_aspera/Aeschynomene_aspera_fruit_3.JPG')}
  },
  {
    "identifier": "16",
    "scientificName": "Paspalum scrobiculatum L.",
    "seedType": "orbicular",
    "plantType": "Grass",
    "lowland": "✔",
    "upland": "",
    "commonName": "Kodo millet",
    "khmerName": "",
    "familyName": "Poaceae",
    "description": "An erect annual or perennial grass, somewhat wiry, 20—100—cm—high.\nStem: culms are slender and without hairs, hollow; nodes swollen, hairy.\nLeaf: 30—cm—long; sheaths loose, hairless, and longer than internodes; ligules membranous, 0.5—3—mm—long.\nInflorescence: consists of 2—5 (15) racemes. Inflorescence 4—8—cm—long, usually spreading; spikelets flattened pale, in 2 rows, about 2—mm—long; caryopsis orbicular, smooth.",
    "habitat": "Grows along field margins and drains of lowland rice fields and also in open grasslands. Also thrives well in cultivated fields, pastures, and roadsides. Is propagated by seeds and occasionally by rooted tillers.",
    "controlMethods": "Cultural control: hand weeding or hoe.\nChemical control: Glyphosate prior to land preparation.",
    "herbicideResistance": "",
    "reference": "http://keyserver.lucidcentral.org/key-server/data/08050103-0a0e-4e01-8a03-040d0c020e0a/media/Html/Paspalum_scrobiculatum.htm",
    "imageCopyright": "",
    "images": { seed: require('../images/plant-images/Paspalum_scrobiculatum/Paspalum_scrobiculatum_seed_1.JPG'), mature: require('../images/plant-images/Paspalum_scrobiculatum/Paspalum_scrobiculatum_mature_1.JPG'), flower: require('../images/plant-images/Paspalum_scrobiculatum/Paspalum_scrobiculatum_flower_1.JPG')}
  },
  {
    "identifier": "17",
    "scientificName": "Fimbristylis dichotoma (L.) Vahl",
    "seedType": "obovoid",
    "plantType": "Sedge",
    "lowland": "✔",
    "upland": "",
    "commonName": "Tall fringe rush, lesser fimbristylis, and two-leaf fimbristylis",
    "khmerName": "",
    "familyName": "Cyperaceae",
    "description": "Annual or perennial, very variable in habit and size of inflorescence, up to 70—cm—high with short rhizome.\nStem: tufted, slender and angular; reaches a height of 10—75—cm; smooth, slightly hairy or glabrous and compressed below the inflorescence.\nLeaf: well developed and about one-half the length of the stem; smooth or more or less hairy; linear to filiform; blades 10—30—cm—long and 0.5—3—mm—wide; ligule a dense fringe of short hairs.\nInflorescence: compound or simple umbel, 3—15—mm—long, composed of loose or dense, few to numerous spikelets; reddish to brownish and ovoid to oblong-ovoid.\nFruit: oblong-ovoid to obovate nut, about 1—mm; 5—10 longitudinal ribs with numerous cross-bars; glossy white to straw-colored, rarely brown.",
    "habitat": "Common in upland areas; also found in rainfed paddy fields, cultivated fields, lawns, and wetland pastures. Reproduces by seeds; flowers year-round; a single plant can produce up to 6,500 seeds.",
    "controlMethods": "Cultural control: handweeding or hoeing at seedling stage.\nChemical control: MCPA or 2,4-D at 20 to 30 days after rice emergence.",
    "herbicideResistance": "",
    "reference": "http://keyserver.lucidcentral.org/key-server/data/08050103-0a0e-4e01-8a03-040d0c020e0a/media/Html/Fimbristylis_dichotoma.htm",
    "imageCopyright": "",
    "images": { seed: require('../images/plant-images/Fimbristylis_dichotoma/Fimbristylis_dichotoma_seed_1.JPG'), mature: require('../images/plant-images/Fimbristylis_dichotoma/Fimbristylis_dichotoma_mature_1.JPG'), flower: require('../images/plant-images/Fimbristylis_dichotoma/Fimbristylis_dichotoma_flower_1.JPG')}
  },
  {
    "identifier": "18",
    "scientificName": "Eclipta prostrata (L.) L.",
    "seedType": "cuneate",
    "plantType": "Broadleaf",
    "lowland": "✔",
    "upland": "✔",
    "commonName": "False daisy",
    "khmerName": "Mok chhneang",
    "familyName": "Asteraceae ",
    "description": "A prostrate or reclining to erect, often branched, annual or perennial herb, 30—100—cm—tall.\nStem: cylindrical, green or purplish, rooting at basal nodes, and often covered with long white hairs.\nLeaf: oblong to lance-shaped, opposite, sessile or short-stalked, with more or less coarse hairs; margins entire or slightly toothed, up to 2—16—cm—long.\nInflorescence: terminal and axillary, about 1—cm across, white or cream, on peduncles to 7—cm—long.\nFruit: achene, densely warted, either brown or black, 2—3—mm—long. ",
    "habitat": "Widespread and adapted to a range of environments. Found in poorly drained wet areas, saline conditions, along streams, in drains and canals of irrigated lowland rice paddies, in waste areas, and in upland fields.\nA single plant can produce as many as 17,000 seeds; germination affected by light, moisture level, pH, and temperature, but seeds have no dormancy.",
    "controlMethods": "Cultural control: cultivation and hand weeding.\nChemical control: preemergence application of oxadiazon or postemergence spraying of either 2,4-D or MCPA reported to be effective. ",
    "herbicideResistance": "",
    "reference": "http://keyserver.lucidcentral.org/key-server/data/08050103-0a0e-4e01-8a03-040d0c020e0a/media/Html/Eclipta_prostrata.htm",
    "imageCopyright": "",
    "images": { seed: require('../images/plant-images/Eclipta_prostrata/Eclipta_prostrata_seed_1.JPG'), mature: require('../images/plant-images/Eclipta_prostrata/Eclipta_prostrata_mature_1.JPG'), flower: require('../images/plant-images/Eclipta_prostrata/Eclipta_prostrata_flower_1.JPG')}
  },
  {
    "identifier": "19",
    "scientificName": "Commelina benghalensis L.",
    "seedType": "cylindric, triquetrous",
    "plantType": "Sedge",
    "lowland": "✔",
    "upland": "✔",
    "commonName": "Tropical spiderwort",
    "khmerName": "Slab tea",
    "familyName": "Cyperaceae",
    "description": "A prostrate or ascending, 30—100—cm—long perennial or annual herb.\nStem: fleshy and rooting at nodes, cylindrical, hairy; basal portions often underground with reduced leaves and modified flowers.\nLeaf: elliptic-ovate, hairy with parallel veins, helically arranged; 2.5—7.5—cm—long; petiole, 6—mm—long, fringed with short and long red hairs.\nInflorescence: spathe enclosing 3—4 violet-blue flowers with 3—4—mm—long green petals, funnel-shaped, compressed, about 1.5—cm—long and wide; some flowers produced from underground stems, whitish, remain unopened throughout their life.\nFruit: a 6—7—mm—long capsule with five seeds.\nSeed: gray-black with a wrinkled surface; appears sugar-coated, 2—mm—long.",
    "habitat": "Favors moist, fertile soil conditions in sunny or lightly shaded locations. Common in upland fields, field margins, and open waste places. A single plant is able to spread over a large area because of its ability to produce adventitious roots at the nodes and its straggling habit.\nIt produces two kinds of flower (floral dimorphism), one on the stems aerially and the other from the underground stem. It also exhibits seed polymorphism, in which the aerial flower produces one large and four small seeds, whereas the underground flower produces one large and two small seeds. Aerial and underground flowers are perfect (bisexual) and can be self-pollinated. Reproduces by seed and vegetatively from underground stems.\nSeedlings emerge after 10—12 days and take 35 days to reach the reproductive stage.",
    "controlMethods": "Cultural control: hand weeding can control this weed effectively.\nChemical control: butachlor as preemergence and propanil or 2,4-D or MCPA as postemergence treatments",
    "herbicideResistance": "",
    "reference": "http://keyserver.lucidcentral.org/key-server/data/08050103-0a0e-4e01-8a03-040d0c020e0a/media/Html/Commelina_benghalensis.htm",
    "imageCopyright": "",
    "images": { seed: require('../images/plant-images/Commelina_benghalensis/Commelina_benghalensis_seed_1.JPG'), mature: require('../images/plant-images/Commelina_benghalensis/Commelina_benghalensis_mature_1.JPG'), flower: require('../images/plant-images/Commelina_benghalensis/Commelina_benghalensis_flower_1.JPG')}
  },
  {
    "identifier": "20",
    "scientificName": "Actinoscirpus grossus (L.f.) Goetgh. & D. A. Simpson",
    "seedType": "Obovoid",
    "plantType": "Sedge",
    "lowland": "✔",
    "upland": "",
    "commonName": "",
    "khmerName": "",
    "familyName": "Cyperaceae",
    "description": "A stout, strongly tillering perennial, up to 300—cm—tall, with long stolons that end in small tubers.\nStem: erect, sharply triangular, with concave sides smooth or slightly rough to the touch, thickened at base.\nLeaf: basal and linear, upper half almost flat, acute and with very gradually tapering point; lower half keeled with 3 sharp projecting angles; 50—80—cm—long.\nInflorescence: 4—17—cm—long terminal corymb, composed of brown, ovoid, and 4—10—mm—long numerous spikelets.\nFruit: broadly obovate nut, smooth, light brown, and 1—1.5—mm—long. ",
    "habitat": "Common in wetland rice, freshwater swamps, and along streams, canals, and drains.\nPropagated by stolons and tubers, rarely by seeds.\nVegetative growth in rice fields is enhanced by increasing water depth to more than 10—cm. Flowering starts 18 weeks after sprouting.",
    "controlMethods": "Cultural control: in preparation for rice, 2—3 rotovations and removal of stolons by harrowing reduce the population of this weed.\nChemical control: Paraquat, diquat, glyphosate, and glufosinate ammonium before crop is established",
    "herbicideResistance": "",
    "reference": "http://keyserver.lucidcentral.org/key-server/data/08050103-0a0e-4e01-8a03-040d0c020e0a/media/Html/Actinoscirpus_grossus.htm",
    "imageCopyright": "",
    "images": { seed: require('../images/plant-images/Actinoscirpus_grossus/Actinoscirpus_grossus_seed_1.JPG'), mature: require('../images/plant-images/Actinoscirpus_grossus/Actinoscirpus_grossus_mature_1.JPG'), flower: require('../images/plant-images/Actinoscirpus_grossus/Actinoscirpus_grossus_flower_1.JPG')}
  },
  {
    "identifier": "21",
    "scientificName": "Schoenoplectus juncoides Roxburgh",
    "seedType": "obovoid",
    "plantType": "Sedge",
    "lowland": "✔",
    "upland": "",
    "commonName": "",
    "khmerName": "",
    "familyName": "Cyperaceae",
    "description": "A tufted, erect, strongly tillering and slender annual or perennial, up to 60—cm—tall.\nStem: erect, smooth, rounded or slightly angular, ribbed and extended 2—10—cm beyond the inflorescence.\nLeaf: reduced to 2—3 membranous leaf, truncated at top sheath, often with a small rudimentary blade.\nInflorescence: 2—5 sessile spikelets, ovoid to oblong, 1—cm or less long, greenish brown or straw-colored to brownish.\nFruit: a shiny black nut, strongly compressed, obovoid and about 2—mm—long. ",
    "habitat": "Found in lowland rice, shallow ponds, streams, and drains.\nEmerges directly from seeds in puddled rice fields; in swampy areas where tillage is minimal, seedlings emerge from vegetative buds. Seed germination increases under anaerobic conditions.",
    "controlMethods": "Cultural: dry rotovation and wet puddling can reduce populations.\nChemical: Pretilachlor, butachlor, thiobencarb, and sulfonylureas are reported to be effective",
    "herbicideResistance": "",
    "reference": "http://keyserver.lucidcentral.org/key-server/data/08050103-0a0e-4e01-8a03-040d0c020e0a/media/Html/Schoenoplectus_juncoides.htm",
    "imageCopyright": "",
    "images": { seed: require('../images/plant-images/Schoenoplectus_juncoides/Schoenoplectus_juncoides_seed_1.JPG'), mature: require('../images/plant-images/Schoenoplectus_juncoides/Schoenoplectus_juncoides_mature_1.JPG')}
  },
  {
    "identifier": "22",
    "scientificName": "Dactyloctenium aegyptium (L.) Willd",
    "seedType": "obovate, triangular",
    "plantType": "Grass",
    "lowland": "✔",
    "upland": "✔",
    "commonName": "Egyptian crowfoot grass",
    "khmerName": "Smao cheung Kras",
    "familyName": "Poaceae ",
    "description": "Annual or rarely perennial grass, 15—60—cm—tall, loosely tufted.\nStem: creeping at base; flowering culms ascending or erect, filled with pith and hairless.\nLeaf: flat or wavy, weak, up to 20—cm—long; both surfaces are sparingly hairy; sheath compressed, glabrous; ligule very short, white, membranous.\nInflorescence: two to seven digitately arranged spikes, often purplish, 1—5—cm—long and 5—7—mm thick; spikelets numerous, crowded, and spreading, 3—mm—long with 3 or 4 flowers.",
    "habitat": "Grows in waste places, field margins, in lightly shaded or sunny areas, drains, and in association with most upland crops. It is propagated mainly by seeds and in warmer regions it flowers year-round.",
    "controlMethods": "Cultural control: hand weeding is effective.\nChemical control: Pendimethalin, oxadiazon as preemergence treatments, or cyhalofop, fenoxaprop, or propanil applied at 3—5 leaf stage of the weed.",
    "herbicideResistance": "",
    "reference": "http://keyserver.lucidcentral.org/key-server/data/08050103-0a0e-4e01-8a03-040d0c020e0a/media/Html/Dactyloctenium_aegyptium.htm",
    "imageCopyright": "",
    "images": { seed: require('../images/plant-images/Dactyloctenium_aegyptium/Dactyloctenium_aegyptium_seed_1.JPG'), mature: require('../images/plant-images/Dactyloctenium_aegyptium/Dactyloctenium_aegyptium_mature_1.JPG'), flower: require('../images/plant-images/Dactyloctenium_aegyptium/Dactyloctenium_aegyptium_flower_1.JPG')}
  },
  {
    "identifier": "23",
    "scientificName": "Rottboellia cochinchinensis (Lour.) W.D. Clayton",
    "seedType": "oblong, ovoid",
    "plantType": "Grass",
    "lowland": "✔",
    "upland": "",
    "commonName": "Itchgrass ",
    "khmerName": "",
    "familyName": "Poaceae",
    "description": "An erect, branched, and coarse annual; up to 350—cm tall.\nStem: stout, branched, with prop roots and spongy inside.\nLeaf: flat and hairy, linear lance-shaped, to about 45 cm long, with distinctive white midrib: sheaths armed with stiff irritating hairs.\nInflorescence: solitary cylindrical spike at terminal points of culm and branches, a \"rat tail\" raceme. Spike 8—15—cm—long, narrowed upward and breaks readily with 6—7—mm—long joints; spikelet paired, lower one is sunken in the cavity of a cylinder, about 4—mm—long rachis joint.",
    "habitat": " It is common in open, well-drained places, dryland field crops, plantation crops, contour banks, roadsides, and vegetables.\nPropagates by seed, may flower year-round in tropics. A serious weed in maize.",
    "controlMethods": "Cultural control: regular cultivation of fields; will not tolerate flooded conditions.\nBiological control: a head smut, Sporisorium (Sphacelotheca) ophiuri, which prevents seed formation, is a potential biological control agent.\nChemical control: preemergence application of pendimethalin or early postemergence treatment with cyhalofop, fenoxaprop, or propanil can be effective. ",
    "herbicideResistance": "",
    "reference": "http://keyserver.lucidcentral.org/key-server/data/08050103-0a0e-4e01-8a03-040d0c020e0a/media/Html/Rottboellia_cochinchinensis.htm",
    "imageCopyright": "",
    "images": { mature: require('../images/plant-images/Rottboellia_cochinchinensis/Rottboellia_cochinchinensis_mature_1.JPG'), flower: require('../images/plant-images/Rottboellia_cochinchinensis/Rottboellia_cochinchinensis_flower_1.JPG'), inflorescence: require('../images/plant-images/Rottboellia_cochinchinensis/Rottboellia_cochinchinensis_inflorescence_1.JPG'), ligule: require('../images/plant-images/Rottboellia_cochinchinensis/Rottboellia_cochinchinensis_ligule_1.JPG')}
  },
  {
    "identifier": "24",
    "scientificName": "Sphenoclea zeylanica Gaertn.",
    "seedType": "oblong",
    "plantType": "Sedge",
    "lowland": "✔",
    "upland": "",
    "commonName": "Gooseweed ",
    "khmerName": "Smao taseav",
    "familyName": "Sphenocleaceae ",
    "description": "An erect, branched herb, 7—150—cm—tall. Fruit: a flat, 4—5—mm—diameter globular capsule.\nSeed: yellowish brown, 0.5—mm—long. \nStem: smooth and fleshy, hollow, much branched and with white, spongy (aerenchymatous) tissues at base.\nLeaf: simple and spirally arranged light green; blades oblong to lance-shaped, narrowed at the tip, 10—cm—long, borne on short stalks.\nInflorescence: green, cylindrical, 7.5—cm—long and dense terminal spike; flowers densely crowded, white to greenish, sessile.",
    "habitat": "Found in wet ground and prefers stagnant water; widespread. Herbaceous annual weed, reproducing by seeds; seeds usually dormant and germination is initiated by light. Flowers throughout the year and sets fruit.",
    "controlMethods": "Cultural control: closed crop canopy limits germination and growth of the weed.\nChemical control: Anilofos, bensulfuron, cinosulfuron, chlorimuron, metsulfuron, prazosulfuron, thiobencarb, oxadiazon, piperophos, and propanil are reported to be effective.",
    "herbicideResistance": "",
    "reference": "http://keyserver.lucidcentral.org/key-server/data/08050103-0a0e-4e01-8a03-040d0c020e0a/media/Html/Sphenoclea_zeylanica.htm",
    "imageCopyright": "",
    "images": { seed: require('../images/plant-images/Sphenoclea_zeylanica/Sphenoclea_zeylanica_seed_1.JPG'), mature: require('../images/plant-images/Sphenoclea_zeylanica/Sphenoclea_zeylanica_mature_1.JPG'), inflorescence: require('../images/plant-images/Sphenoclea_zeylanica/Sphenoclea_zeylanica_inflorescence_1.JPG')}
  },
  {
    "identifier": "25",
    "scientificName": "Chromolaena odorata (L.) R. M. King & H. Robinson",
    "seedType": "Linear",
    "plantType": "Broadleaf",
    "lowland": "",
    "upland": "✔",
    "commonName": "Siam weed",
    "khmerName": "kântrèang'khaêt; tönöör",
    "familyName": "Asteraceae",
    "description": "An upright (erect) or sprawling shrub forming thickets and usually growing 1.5 to 3 m tall in the open. However it may reach greater heights (6-20 m) when climbing over trees and other taller vegetation.\n\nThe slender stems are generally yellowish-green and somewhat hairy (pubescent), but become woody towards the base of the plant. These stems grow up to 7 m or more in length and several are usually produced from the plants long-lived root-stock (crown). They are much-branched, with the side (lateral) branches usually being produced in pairs in the leaf forks (axils).\n\nThe oppositely arranged leaves (5-12 cm long and 3-7 cm wide) are triangular or egg-shaped in outline with broad end at base (ovate) and have a pointed tip (acute apex). They are hairy (pubescent) on both surfaces and have coarsely toothed (serrated) margins. These leaves are borne on stalks (petioles) up to 6 cm long (usually 10-15 mm), and give off a strong odour when crushed.\n\nThe small flower-heads (capitula) do not have any 'petals' (ray florets) and are borne in dense clusters at the ends of the branches (in terminal panicles). These flower-heads (about 10 mm long and 3 mm wide) are pale pink or pale mauve in colour (sometimes appearing whitish when older) and consist of numerous (15-30) tiny flowers (tubular florets). These tiny flowers (10-12 mm long) are surrounded by several layers of overlapping slender bracts (an involucre) 8-9 mm long. Each flower-head (capitulum) is borne on a stalk (peduncle) 10-30 mm long.\n\nThe black or dark brown 'seeds' (achenes) are 4-5 mm long and topped with a ring (pappus) of white to brownish coloured hairs (5-6 mm long).",
    "habitat": "C. odorata can grow in areas with an annual rainfall below 1000 mm, provided the dry season is not too long. It is limited to around 2000 m altitude, which might indicate that C. odorata cannot endure frost. It grows on soils ranging from sand dunes to heavy clays. The most common form of Siam weed flowers from May to\nJuly and again in September to October. Siam weed produces huge numbers of windborne seeds\nwithin 8–10 weeks after flowering. Siam weed dies back in the dry season but re-shoots\nafter rain. ",
    "controlMethods": "Mechanical control: Physical removal of the basal/root ball is very effective. \nand recommended for smaller infestations. However, it is\nextremely important to make sure the removed plant does\nnot remain in contact with soil, as any contact will result\nin the plant re-shooting.                             Chemical control: Herbicide application, such as  Glyphosate, at the correct rates, and before\nflowering, will provide effective control if carried out\nregularly. Incorrect application can lead to herbicide pruning,\nwhich will allow the plant to re-shoot. Always read the label\nbefore using any herbicide.",
    "herbicideResistance": "",
    "reference": "http://www.cabi.org/isc/datasheet/23248 http://keys.lucidcentral.org/keys/v3/eafrinet/weeds/key/weeds/Media/Html/Chromolaena_odorata_(Chromolaena).htm https://www.daf.qld.gov.au/__data/assets/pdf_file/0015/50028/IPA-Siam-Weed-PP49.pdf",
    "imageCopyright": "",
    "images": { seed: require('../images/plant-images/Chromolaena_odorata/Chromolaena_odorata_seed_1.JPG'), mature: require('../images/plant-images/Chromolaena_odorata/Chromolaena_odorata_mature_1.JPG'), flower: require('../images/plant-images/Chromolaena_odorata/Chromolaena_odorata_flower_2.JPG')}
  },
  {
    "identifier": "26",
    "scientificName": "Murdannia nudiflora (L.) Brenan",
    "seedType": "triangular/ deltoid",
    "plantType": "Broadleaf",
    "lowland": "✔",
    "upland": "",
    "commonName": "doveweed",
    "khmerName": "",
    "familyName": "Commelinaceae",
    "description": "\nIt is an annual or perennial herb, 8-115 cm tall, with a basal leaf rosette, disappearing or absent in older plants, with one to several creeping leafy branches, being either erect, semi-erect, ascendant, or at the base. Leaves are alternately arranged, sessile, larger ones linear-lanceolate, smaller ones oblong-ovate, glabrous, or with sparsely-arranged trichomes or hairs, 1.7-28 or 1.7-45 cm x 5-25 mm, with a broad leaf base, acute apex, short leaf sheath, and villous. Roots are normal, not swollen. Inflorescences terminally- or axillary-arranged, either unbranched or with 2-3 branches, no large cucullate bracts; bracts 25-35 mm oblong-cucullate, rather thin, membranous, caducous, located at the base of 25-40 mm long, glabrous pedicels, sepals 3, green, oblong, obtuse, glabrous, 3.5-5.0 mm long, petals 3, oblong to ovate-oblong, obtuse, purplish to magenta in colour, 4.5-5.5 mm long. Stamens free, 2 fertile with densely long-hairy filaments and bluish-coloured anthers; staminoids 4, with long-bearded filaments, the 3 opposite the petals with thickened, 3-lobed, light yellow coloured top, the fourth much reduced in size. The ovary is glabrous. Fruits condensed, ellipsoid-globose, shortly acuminate, glabrous, 4-6 mm in diameter, 3-loculate, each cell with 1-2 seeds, rarely with more than 6 seeds per fruit. Seeds smooth to coarse reticulate, ribbed.",
    "habitat": "M. nudiflora prevail under wet or waterlogged conditions where soil pH is often low (acidic). It appears tolerant to a wide range of conditions, in either open situations or in rather deeply shaded sites, and at low altitude or at altitudes of 1800 m or higher. \n",
    "controlMethods": "Cultural control: Burning of straw, stubble and weeds after harvesting rice prior to tillage operations and replanting/sowing of new crops. Mechanical control: hand weeding, hoeing or cutting with machete. Chemical control: bentazone applied as an early post-emergence herbicide either singularly or in mixtures was particularly effective, metribuzin applied as pre-emergence.",
    "herbicideResistance": "",
    "reference": "http://www.cabi.org/isc/datasheet/35180",
    "imageCopyright": "",
    "images": { seed: require('../images/plant-images/Murdannia_nudiflora/Murdannia_nudiflora_seed_1.JPG'), ligule: require('../images/plant-images/Murdannia_nudiflora/Murdannia_nudiflora_ligule_1.JPG')}
  },
  {
    "identifier": "27",
    "scientificName": "Aeschynomene americana L.",
    "seedType": "Reniform",
    "plantType": "Broadleaf",
    "lowland": "✔",
    "upland": "✔",
    "commonName": "American joint vetch",
    "khmerName": "",
    "familyName": "Fabaceae",
    "description": "An erect-ascending, annual or short-lived perennial, shrub-like legume, 1 to 2 m tall. Stems hairless, often hard but pithy in the lower regions; upper sections hairy, usually glandular. Leaves 3 to 7 cm long. Leaflets 8 to 38 pairs, 5 to 15 mm long, 1 to 2 mm wide, linear or linear to oblong, sensitive, folding together when touched. Stipules persistent, linear-lanceolate, 1 to 2 cm long. Inflorescence a loose, few-flowered raceme, often branched. Calyx about 4 mm long, deeply two-lipped. Corolla varying in colour from white tinged with mauve or light violet to purple to flesh coloured, sometimes pinkish orange, 6 to 10 mm long. Pod usually slightly curved, four to eight jointed, up to 4 cm long, the upper margin entire, the lower deeply indented at each segment joint; each segment one-seeded; semi-circular, about 4 mm long. Seeds grey-green to dark and light brown.",
    "habitat": "Found on soils ranging from gravels and sands to clays, but mostly on finer-textured soils.  Soil pH at collection sites is mostly 6-7, but ranges from as low as 4 to as high as 8.  Mostly in moderately fertile soils with pH from 5.5-7.0.",
    "controlMethods": "This can be used for cattle grazing for its high nutritive value for livestock. Chemical control: Post emergence herbicide such as bentazone and acifluorfen. ",
    "herbicideResistance": "",
    "reference": "http://www.tropicalforages.info/key/Forages/Media/Html/Aeschynomene_americana.htm http://www.fao.org/ag/agp/agpc/doc/gbase/DATA/pf000001.htm",
    "imageCopyright": "",
    "images": { seed: require('../images/plant-images/Aeschynomene_americana/Aeschynomene_americana_seed_1.JPG'), mature: require('../images/plant-images/Aeschynomene_americana/Aeschynomene_americana_mature_2.JPG'), flower: require('../images/plant-images/Aeschynomene_americana/Aeschynomene_americana_flower_3.JPG'), fruit: require('../images/plant-images/Aeschynomene_americana/Aeschynomene_americana_fruit_2.JPG')}
  },
  {
    "identifier": "28",
    "scientificName": "Alysicarpus monilifer L.",
    "seedType": "Reniform",
    "plantType": "Broadleaf",
    "lowland": "✔",
    "upland": "✔",
    "commonName": "",
    "khmerName": "Duem santeah omal",
    "familyName": "Fabaceae",
    "description": "Low growing, much branched, annual or perennial herb, 5–15 (–50) cm tall.  Leaves simple;  ovate, elliptical or lanceolate, cordate at the base, 2.5–7.5 cm long, prominently nerved, glabrous or sparsely pubescent beneath.  Racemes spicate, axillary and terminal, 1–15 cm long;  flowers lax to dense along racemes.  Pods distinctly moniliform, 3- to 5-jointed, 1–2 cm long, calyx not longer than first joint;  glabrous or sparsely pubescent;  articles 2.5–3 mm long and 2–3 mm wide, with a smooth to reticulate surface sculpture.",
    "habitat": "Grows on a wide range of soil types from deep sands and stony soils to cracking clays with a pH range of 5.5–8.",
    "controlMethods": "",
    "herbicideResistance": "",
    "reference": "",
    "imageCopyright": "",
    "images": { seed: require('../images/plant-images/Alysicarpus_monilifer/Alysicarpus_monilifer_seed_1.JPG'), mature: require('../images/plant-images/Alysicarpus_monilifer/Alysicarpus_monilifer_mature_2.JPG'), flower: require('../images/plant-images/Alysicarpus_monilifer/Alysicarpus_monilifer_flower_2.JPG')}
  },
  {
    "identifier": "29",
    "scientificName": "Sesbania bispinosa (Jacquin) W. Wight",
    "seedType": "oblong",
    "plantType": "Broadleaf",
    "lowland": "✔",
    "upland": "",
    "commonName": "Sesbania pea",
    "khmerName": "",
    "familyName": "Fabaceae",
    "description": "a herb, sometimes suffrutescent, (min. 0.6) 1-3 m\ntall; young stem glabrous or nearly so, sparsely to rather densely aculeate.\nLeaves with axis usually aculeate, to about (min. 5.5) 9.5-29.5 (max. 35)\ncm long, 20-100 foliate; stipules linear lanceolate, 5-10 mm long, adaxially\npubescent, pilose on margins and above, late caducous; petiole 2-20 mm\nlong; leaflets oblong to oblong linear, 0.75-2 (max. 2.6) cm x 1.5-3 (max.\n5) mm, obtuse, mucronate, glabrous on both surfaces, in (min. 10) 20-50\n(55 max) pairs; base obtuse; apex obtuse, emarginate, usually apiculate,\nglabrescent; stipels minute, caducous; inflorescence and pedicels often\naculeate; bracts and bracteoles linear, caducous.\nRaceme (min. 1) 2.5-15 (max. 16.5) cm long, 1-12 (max. 14) flowered;\npeduncle (min. 0.5) 1.5-4 (max. 6) long, glabrous; flowers 10-12 (max. 13)\nmm long; pedicels 6-11 mm long; calyx about 3-5 mm long, 3-4 mm wide,\nglabrous except when puberulent along the margin and inside teeth; teeth\ntriangular 0.5-1 mm long; corolla yellow with brownish markings; vexillum\nwith wedge-shaped, truncate basal appendages within; standard rounded\nto obovate, 1-1.5 cm x 8-14 mm, pale yellowish, spotted brownish or\npurplish; wings oblong, 1-1.25 cm x 2.5-3 mm, yellow; keel straight, 1-1.3\ncm x 3.5-5 mm; staminal tube up to 12 mm long, free filament parts 2-4\nmm long; pistil glabrous; style 2-3 mm long; stigma capitate.\nFruit a glabrous pod, somewhat curved, about 12.5-25 cm long, 2-3 mm\nwide, beaked, 28-45 seeded, constricted between the seeds, with septa\nabout 5 mm apart; seeds pale brown, olive-green or greenish-black,\nellipsoid, about 3 x 1.5 x 1.1 mm.",
    "habitat": "Marshes, ditches, river margins; also a weed in cultivations on alluvial land, especially in rice fields; often in saline areas; flood-plains, seasonally inundated depressions, sandbanks of brackish lagoons; occasionally in open miombo woodland[",
    "controlMethods": "Can be used as fodder for cattle. Mature seeds can be cooked for consumption. The stem is used as fiber for paper industry and water-related equipment such as sail and fishing net. Can be made into green manure for rice field.",
    "herbicideResistance": "",
    "reference": "http://www.worldagroforestry.org/treedb/AFTPDFS/Sesbania_bispinosa.PDF http://tropical.theferns.info/viewtropical.php?id=Sesbania+bispinosa http://www.feedipedia.org/node/255",
    "imageCopyright": "",
    "images": { seed: require('../images/plant-images/Sesbania_bispinosa/Sesbania_bispinosa_seed_1.JPG'), mature: require('../images/plant-images/Sesbania_bispinosa/Sesbania_bispinosa_mature_1.JPG')}
  },
  {
    "identifier": "30",
    "scientificName": "Lindernia antipoda (L.) Alston",
    "seedType": "triangular, ovoid, deltoid",
    "plantType": "Broadleaf",
    "lowland": "✔",
    "upland": "",
    "commonName": "Sparrow False Pimpernel ",
    "khmerName": "",
    "familyName": "Linderniaceae",
    "description": "Annuals to 30 cm tall. Roots fibrous, fascicled. Stems suberect or prostrate basally and rooting from lower nodes then ascending, many branched, channeled, glabrous. Petiole short and wide; leaf blade oblong, oblong-lanceolate, oblong-oblanceolate, or linear-lanceolate, 0.8-4 X 0.6-2 cm, glabrous, base cuneate and decurrent, margin obscurely to sharply serrate or subentire, apex acute to rounded. Racemes terminal, to 15 cm, 2-20-flowered; bracts subulate. Pedicel to 1.5 cm, ascending, spreading, to deflexed in fruit. Calyx lobed to base; lobes lanceolate, hispidulous along midrib and edges. Corolla purple, purplish white, or white, to 1 cm; tube to 7 mm; lower lip 3-lobed, lobes subequal; upper lip 2-lobed. Fertile stamens 2, posterior; filaments unapendaged. Reduced stamens 2, anterior; filaments slightly curved, glandular. Stigma lamellate. Capsule cylindric, 2 X or more as long as persistent calyx. Seeds brown, irregularly triangular-ovoid; seed coat reticulate. Fl. and fr. spring-autumn.",
    "habitat": "lowland and upland rice fields, wet grassland, sunny or shaded, moist or swampy localities, also near villages and in open forest or ditches, on arable land and irrigated or rain fed rice fields",
    "controlMethods": "Mechanical control: hand weeding. Chemical control: application of pre-sowing and postemergence herbicide e.g. 2,4 D, or preemergence herbicide e.g. butachlor",
    "herbicideResistance": "",
    "reference": "http://www.efloras.org/florataxon.aspx?flora_id=2&taxon_id=200020717 http://www.plantwise.org/KnowledgeBank/Datasheet.aspx?dsid=30861 http://eol.org/pages/484450/overview",
    "imageCopyright": "",
    "images": { seed: require('../images/plant-images/Lindernia_antipoda/Lindernia_antipoda_seed_1.JPG'), mature: require('../images/plant-images/Lindernia_antipoda/Lindernia_antipoda_mature_1.JPG'), flower: require('../images/plant-images/Lindernia_antipoda/Lindernia_antipoda_flower_1.JPG')}
  },
  {
    "identifier": "31",
    "scientificName": "Ipomoea obscura (L.) Ker Gawler",
    "seedType": "triquetrous",
    "plantType": "Broadleaf",
    "lowland": "",
    "upland": "✔",
    "commonName": "White morning glory",
    "khmerName": "Voir mouy lib",
    "familyName": "Convolvulaceae",
    "description": "Herbs twining; axial parts glabrous, spreading pubescent, or almost woolly. Stems thinly angular, 1-2 m. Petiole 1.5-3.5 cm; leaf blade cordate-circular or ovate, occasionally reniform, 2-8 X 1.6-8 cm, glabrous or sparsely pilose, base cordate, margin entire or minutely undulate, apex attenuate, acute. Inflorescences 1-3-flowered; peduncle almost filiform, 1.4-4 cm; bracts subulate, ca. 1.5 mm. Pedicel 0.8-2 cm, subglabrous, thickened and recurved in fruit distally. Sepals reflexed in fruit, elliptic-ovate, subequal, 4-5 mm, glabrous or ± pubescent, mucronulate, outer ones whitish margined. Corolla white or pale yellow, with darker midpetaline bands and a purple center, funnelform, 2-2.5 cm. Stamens included; filaments very unequal. Pistil included; ovary glabrous. Stigma 2-lobed. Capsule conical-ovoid or ± globose, 6-8 mm in diam., apiculate. Seeds black-brown, 4-5 mm, densely gray-brown tomentellous.",
    "habitat": "White morning glory grows in dry, open, disturbed areas at low elevations.",
    "controlMethods": "",
    "herbicideResistance": "",
    "reference": "",
    "imageCopyright": "",
    "images": { seed: require('../images/plant-images/Ipomoea_obscura/Ipomoea_obscura_seed_1.JPG'), mature: require('../images/plant-images/Ipomoea_obscura/Ipomoea_obscura_mature_1.JPG'), flower: require('../images/plant-images/Ipomoea_obscura/Ipomoea_obscura_flower_1.JPG')}
  },
  {
    "identifier": "32",
    "scientificName": "Merremia hederacea (N. L. Burman) H. Hallier",
    "seedType": "triquetrous",
    "plantType": "Broadleaf",
    "lowland": "✔",
    "upland": "",
    "commonName": "",
    "khmerName": "",
    "familyName": "Convolvulaceae",
    "description": "Herbs, twining or prostrate; axial parts often minutely tuberculate. Stems glabrous or sparsely hirsute, rooting at nodes. Petiole 0.5-5 cm, glabrous or pubescent; leaf blade cordate-ovate, 1.5-7.5 X 1-5 cm, subglabrous to sparsely puberulent, base cordate or broadly cordate, margin entire, irregularly crenate, or 3-lobed. Inflorescences (1-) or few to many flowered, umbelliform, cymose in fruit; peduncle (0.3-)0.8-5 cm, thicker than petiole; bracts early deciduous, narrowly obovate. Pedicel 2-5 mm. Sepals broadly obovate to spatulate or oblong, reflexed in fruit, unequal; outer 2 sepals 3.5-4 mm; inner 3 ca. 5 mm, glabrous, apex emarginate and distinctly mucronate, mucro directed outward. Corolla yellow, campanulate, 6-10 mm, outside glabrous, inside villous basally. Stamens ca. as long as corolla; filaments sparsely villous basally. Ovary globose, glabrous; stigma globose. Capsule depressed globose or broadly conical, 5-6 mm, reticulate (but not coarsely) wrinkled. Seeds trigonous-globose, 2.5-3.5 mm, puberulent to glabrous or woolly along angles and at hilum. 2n = 30*.",
    "habitat": " Altitudinal range from near sea level to 150 m. Lives in clay, mud,swamps and floodplains.",
    "controlMethods": "",
    "herbicideResistance": "",
    "reference": "",
    "imageCopyright": "",
    "images": { seed: require('../images/plant-images/Merremia_hederacea/Merremia_hederacea_seed_1.JPG'), mature: require('../images/plant-images/Merremia_hederacea/Merremia_hederacea_mature_1.JPG'), flower: require('../images/plant-images/Merremia_hederacea/Merremia_hederacea_flower_2.JPG')}
  },
  {
    "identifier": "33",
    "scientificName": "Cyperus compactus Retzius",
    "seedType": "oblong",
    "plantType": "Sedge",
    "lowland": "✔",
    "upland": "",
    "commonName": "Compact sedge",
    "khmerName": "",
    "familyName": "Cyperaceae",
    "description": "Caespitose perennial, 40-90 cm; with tillers. Stem 2.5-4 mm diam., obtusely trigonous, smooth. Leaves equalling or longer than stem; sheaths up to 20 cm, yellow-brown, often with reddish tint, soft, mouth margin somewhat concave; blades to more than 80 cm, 4-7 mm wide, greyish green, keeled, margins slightly revolute, margins and keel smooth or slightly scabrous, apex long-attenuate, trigonous, scabrous or nearly smooth. Inflorescence a rounded anthelodium, 8-10(-20) cm diam., primary branches 5-10, up to 10 cm, spreading, bracts 3-5 foliose, up to 50 cm; secondary anthelodia up to 5 cm diam., rounded with 3-5 bracts up to 30 mm; tubular prophyll up to 15 mm, yellow-brown often with reddish tint, bi-nerved, nerves with flat, scabrous arista up to 4 mm; tertiary anthelodia may be present; cluster of spikes 7-16 mm, nearly globose, with from c. 30 to more than 50 spreading, spirally arranged spikes, occasionally two sessile closely together. Spikes 5-7.5 x 0.5-0.8 mm, terete, brown, with 7 glumes, lowest sterile, next three fertile; rachis widely winged; glume-like bract c. 1 mm, brown, acute; glume-like prophyll c. 0.8 mm; glumes 2-3 mm, with rounded back, brown or reddish brown, mid-nerve ending in rounded apex, sides nerved, margins narrowly scarious. Stamens 2. Nut 2.3-2.4 x 0.3-0.4 mm, trigonous, slightly curved, plano-convex, brown, with persistent style-base c. 0.4 mm, finely reticulate and papillose.",
    "habitat": "Growing in shallow waters in seasonally flooded places, swamps, wet rice fields, marshes, ditches, river banks, often gregarious and forming strands",
    "controlMethods": "",
    "herbicideResistance": "",
    "reference": "http://www.efloras.org/florataxon.aspx?flora_id=5&taxon_id=242101113",
    "imageCopyright": "",
    "images": { seed: require('../images/plant-images/Cyperus_compactus/Cyperus_compactus_seed_1.JPG'), mature: require('../images/plant-images/Cyperus_compactus/Cyperus_compactus_mature_1.JPG'), flower: require('../images/plant-images/Cyperus_compactus/Cyperus_compactus_flower_2.JPG')}
  },
  {
    "identifier": "34",
    "scientificName": "Schoenoplectus supinus (L.) Palla",
    "seedType": "obovoid",
    "plantType": "Sedge",
    "lowland": "✔",
    "upland": "",
    "commonName": "Dwarf clubrush",
    "khmerName": "",
    "familyName": "Cyperaceae ",
    "description": "Annual plant forming tufts, 5–30 cm tall. Roots are fibrous, small. Stem 0.8–2 mm diameter, terete or distal parts obscurely trigonous, grooved, green or greyish green, smooth. Sheaths up to 65 mm long, 2–3; ligule up to 0.8 mm long, scarious; blades reduced to mucro or, in uppermost sheath, most often green, up to 50 mm long. Inflorescence 7–20 mm diameter, congested to spherical group of (1–)3–15 spikes. Spikes 5–12 mm, ovoid; glumes rather tightly imbricating, 2–4 mm, cymbiform, brown or reddish brown. Perianth reduced, bristles 3–4, occasionally elongated, unequal, longest shorter than fruit; stamens 3, anther 0.5–0.7 mm long; stigmas 3. Achene ca 1.5 x 1 mm, widely obovoid, apiculate, black brown. The species flowers from June to August.",
    "habitat": "",
    "controlMethods": "",
    "herbicideResistance": "",
    "reference": "",
    "imageCopyright": "",
    "images": { seed: require('../images/plant-images/Schoenoplectus_supinus/Schoenoplectus_supinus_seed_1.JPG'), mature: require('../images/plant-images/Schoenoplectus_supinus/Schoenoplectus_supinus_mature_1.JPG')}
  },
  {
    "identifier": "35",
    "scientificName": "Scleria lithosperma (L.) Swartz",
    "seedType": "obovoid",
    "plantType": "Sedge",
    "lowland": "✔",
    "upland": "",
    "commonName": "Nutrush",
    "khmerName": "Tasat",
    "familyName": "Cyperaceae",
    "description": "Plants perennial; rhizomes short, nodulose, aromatic when fresh. Culms in tufts, slender, 30–90(–115) cm, glabrous or slightly scabrous. Leaves: sheaths purplish, wingless, weakly ribbed, finely pilose or nearly glabrous; contra-ligules reddish, triangular, rigid, distinctly ciliate; blades distinctly grayish green and revolute when dry, linear, attenuate, keeled, 1–3(–5) mm wide, shorter than culms. Inflorescences: axillary 1–3, terminal 1, quite lax; stalked spikes or panicles 2–4, terminal one 3–4.5(–8.5) cm with 2–7 open fascicles 2–6(–9) mm wide, of 1–4 spikelets; bracts subtending and overtopping inflorescence leaflike, broadly attenuate, scabrous. Spikelets bisexual (an occasional terminal staminate spikelet), few flowered, 3–5 mm; staminate scales lanceolate, pistillate scales ovate-acuminate, with prominent green keel. Achenes whitish or gray between angles, obscurely trigonous, ovoid or globose, 2–2.5(–3) mm, smooth, base broadly attenuate, somewhat depressed between angles, trigonous, not porose, apex umbonate; hypogynium obsolete, reduced to distinct brown band at base of achene.",
    "habitat": "",
    "controlMethods": "",
    "herbicideResistance": "",
    "reference": "",
    "imageCopyright": "",
    "images": { seed: require('../images/plant-images/Scleria_lithosperma/Scleria_lithosperma_seed_2.JPG'), mature: require('../images/plant-images/Scleria_lithosperma/Scleria_lithosperma_mature_1.JPG'), flower: require('../images/plant-images/Scleria_lithosperma/Scleria_lithosperma_flower_1.JPG')}
  },
  {
    "identifier": "36",
    "scientificName": "Pentapetes phoenicea  L.",
    "seedType": "triquetrous",
    "plantType": "Broadleaf",
    "lowland": "✔",
    "upland": "",
    "commonName": "Noon Flower",
    "khmerName": "Krachib",
    "familyName": "Malvaceae",
    "description": "Annual herbs, 0.5-1 m tall, sparsely stellate hairy. Petiole 1-2.5 cm; leaf blade linear-lanceolate, 5-10 × 1-2 cm, base broadly cuneate, rounded or truncate, margin crenate, apex acuminate. Flowers opening at noon, closing at dawn. Calyx lobes lanceolate, ca. 1 cm, abaxially stellate velutinous and hispid. Petals red, broadly ovate, ca. 12 mm. Staminodes tongue-shaped, 12-13 × ca. 1 mm. Ovary ovoid, villous; ovules 8-12 per cell; style filiform, glabrous, ca. 1 cm. Capsule nearly globose, ca. 1.2 cm in diam., densely stellate hairy and hispid, shorter than persistent calyx",
    "habitat": "Moist environment",
    "controlMethods": "Mechanical control: Hand weeding. Chemical control: application of oxidiazon-2,4 D and ioxynil-2,4 D ",
    "herbicideResistance": "",
    "reference": "http://efloras.org/florataxon.aspx?flora_id=600&taxon_id=200013821 https://books.google.com.au/books?id=YKZCQ-KLgdwC&pg=PA585&lpg=PA585&dq=Pentapetes+phoenicea+broadleaf&source=bl&ots=l--LthXsa-&sig=jO3LK21mz4j2Jm5EIhPWDajDxe4&hl=en&sa=X&ved=0ahUKEwjb2Y7Tn5DSAhWBXrwKHeOVAmIQ6AEIIjAB#v=onepage&q=Pentapetes%20phoenicea%20broadleaf&f=false",
    "imageCopyright": "",
    "images": { seed: require('../images/plant-images/Pentapetes_phoenicea/Pentapetes_phoenicea_seed_1.JPG'), mature: require('../images/plant-images/Pentapetes_phoenicea/Pentapetes_phoenicea_mature_2.JPG'), flower: require('../images/plant-images/Pentapetes_phoenicea/Pentapetes_phoenicea_flower_4.JPG')}
  },
  {
    "identifier": "37",
    "scientificName": "Phyllanthus urinaria L.",
    "seedType": "triquetrous",
    "plantType": "Broadleaf",
    "lowland": "✔",
    "upland": "✔",
    "commonName": "Shatterstone",
    "khmerName": "Brork phlair",
    "familyName": "Phyllanthaceae",
    "description": "Trees, shrubs, or herbs, mostly monoecious, less often dioecious; branching often \"phyllanthoid\": main stems with spiral phyllotaxy, ultimate branchlets sometimes clustered on short shoots, resembling pinnate leaves and often deciduous as a unit, less often stems all similar with spiral or distichous phyllotaxy; hairs simple, often absent, rarely branched. Leaves alternate, often reduced and scalelike on main stems, strongly distichous on leafy stems; stipules small, deciduous or persistent; petiole short; leaf blade simple, margin entire, venation pinnate. Inflorescences axillary, sometimes at leafless nodes, solitary or in fascicles, cymes, glomerules, racemes, or panicles; pedicels delicate. Male flowers: sepals (2 or)3-6, in 1 or 2 series, free, imbricate, margin entire, eroded, denticulate or fimbriate; petals absent; disk glands 3-6, usually free; stamens 2-6; filaments free or connate; anthers 2-locular, extrorse, thecae 2, connectives obscure, longitudinally or horizontally dehiscent, rarely obliquely so; pistillode absent. Female flowers: sepals as in male or more; disk glands usually small, free or connate into an annulus or urn-shape, surrounding ovary; ovary smooth or less commonly roughened, bullate, or hairy, 3(-12)-locular; ovules 2 per locule; styles 3(-12), apex 2-lobed or 2-branched, rarely entire, erect, spreading, or recurved. Fruit usually a capsule, globose or depressed globose, smooth or warty, dehiscent into 3 2-valved cocci when mature, less often a fleshy berry or drupe; columella persistent. Seeds without caruncle or aril, trigonous, surface smooth, sculptured or striate; seed-coat dry crustaceous, endosperm whitish, cartilaginous; embryo straight or slightly curved; cotyledons usually considerably broader than radical. x = 13.",
    "habitat": "A common weed of waste places, clearings, gardens, along paths, but is also found in evergreen forest and bamboo forest. It grows on well drained, fertile, sandy soils, sometimes on limestone, often in humid places or even in marshy ground, up to 1500 m altitude.",
    "controlMethods": "",
    "herbicideResistance": "",
    "reference": "http://www.efloras.org/florataxon.aspx?flora_id=2&taxon_id=125179 http://publish.plantnet-project.org/project/riceweeds_en/collection/collection/information/details/PYLUR",
    "imageCopyright": "",
    "images": { seed: require('../images/plant-images/Phyllanthus_urinaria/Phyllanthus_urinaria_seed_1.JPG'), mature: require('../images/plant-images/Phyllanthus_urinaria/Phyllanthus_urinaria_mature_2.JPG'), fruit: require('../images/plant-images/Phyllanthus_urinaria/Phyllanthus_urinaria_fruit_1.JPG')}
  },
  {
    "identifier": "38",
    "scientificName": "Phyllanthus virgatus G. Forster",
    "seedType": "triquetrous-",
    "plantType": "Broadleaf",
    "lowland": "✔",
    "upland": "✔",
    "commonName": " Seed-under-leaf",
    "khmerName": "Brork phlair",
    "familyName": "Phyllanthaceae",
    "description": "Annual herbs, usually erect, sometimes prostrate, to 60(-100) cm tall, monoecious, glabrous throughout; stem usually slightly woody at base; branchlets angled. Stipules membranous, ovate-triangular, ca. 1 mm, brown; petiole short, nearly absent; leaf blade thinly leathery, linear-lanceolate, oblong, or narrowly elliptic, 5-25 × 2-7 mm, base slightly obliquely rounded, apex obtuse or acute; midrib raised abaxially, flattened adaxially, lateral veins obscure. Plants monoecious. Inflorescences bisexual axillary fascicles usually with 2-4 male and 1 female flower. Male flowers: pedicels ca. 2 mm; sepals 6, broadly ovate or rotund, ca. 0.5 mm; disk glands 6, oblong; stamens 3; filaments free; anthers subglobose. Female flowers: pedicels ca. 5 mm; sepals 6, ovate-oblong, ca. 1 mm, reflexed, purple with whitish membranous margins, persistent in fruit; disk orbicular, undivided; ovary globose, 3-celled, with raised scales, rarely smooth; styles 3, bifid nearly to base, usually recurved. Fruiting pedicels 5-12 mm; capsules oblate, 2-3 mm in diam., purple, with raised scales or smooth. Seeds trigonous, 1.2-1.5 mm, finely warty. Fl. Apr-May, fr. Jun-Nov.",
    "habitat": "A weed of roadsides, grassy places, arable land and upland rice fields; at elevations up to 750 metres",
    "controlMethods": "",
    "herbicideResistance": "",
    "reference": "http://www.efloras.org/florataxon.aspx?flora_id=2&taxon_id=242337488 http://tropical.theferns.info/viewtropical.php?id=Phyllanthus%20virgatus",
    "imageCopyright": "",
    "images": { seed: require('../images/plant-images/Phyllanthus_virgatus/Phyllanthus_virgatus_seed_1.JPG'), mature: require('../images/plant-images/Phyllanthus_virgatus/Phyllanthus_virgatus_mature_1.JPG'), fruit: require('../images/plant-images/Phyllanthus_virgatus/Phyllanthus_virgatus_fruit_1.JPG')}
  },
  {
    "identifier": "39",
    "scientificName": "Digitaria bicornis Roemer & J.A. Schultes ex Loud.",
    "seedType": "elliptic",
    "plantType": "Grass",
    "lowland": "✔",
    "upland": "✔",
    "commonName": "Finger grass, Asian crabgrass",
    "khmerName": "Smao sambok mon",
    "familyName": "Poaceae",
    "description": "Annual. culms decumbent, rooting at lower nodes, 30–60 cm tall. Leaf sheaths glabrous or lower sheaths papillose-pilose; leaf blades linear, 2.5–15 × 0.2–0.9 mm, usually scabrid on both surfaces, rarely sparsely pilose; ligule 1–3.5 mm. Inflorescence digitate or subdigitate; racemes 2–5, 4–14 cm; spikelets paired, imbricate; rachis triquetrous, ca. 1 mm wide, winged. Spikelets lanceolate, ca. 3 mm, those of a pair usually different; lower spikelet glabrous, upper spikelet pubescent; lower glume very small, almost absent or up to 0.4 mm, triangular or bifid, veinless; upper glume lanceolate, ca. 2/3 length of spikelet, 3-veined, pilose; lower lemma as long as spikelet, 7-veined, lower spikelet with equidistant veins, upper spikelet with wider glabrous interspaces on either side of midvein, lateral veins crowded near margins, rows of silky hairs between lateral veins, usually also setose, the hairs spreading halo-like at maturity; upper lemma yellowish, slightly shorter than spikelet. Fl. and fr. May–Sep. 2n = 54, 72.",
    "habitat": "",
    "controlMethods": "",
    "herbicideResistance": "",
    "reference": "http://www.efloras.org/florataxon.aspx?flora_id=2&taxon_id=200025246",
    "imageCopyright": "",
    "images": { seed: require('../images/plant-images/Digitaria_bicornis/Digitaria_bicornis_seed_2.JPG'), mature: require('../images/plant-images/Digitaria_bicornis/Digitaria_bicornis_mature_1.JPG'), flower: require('../images/plant-images/Digitaria_bicornis/Digitaria_bicornis_flower_1.JPG'), spikelet: require('../images/plant-images/Digitaria_bicornis/Digitaria_bicornis_spikelet_1.jpeg')}
  },
  {
    "identifier": "40",
    "scientificName": "Hymenachne amplexicaulis (Rudge) Nees",
    "seedType": "ovoid",
    "plantType": "Grass",
    "lowland": "✔",
    "upland": "",
    "commonName": "Marsh grass",
    "khmerName": "",
    "familyName": "Poaceae",
    "description": "Perennial. Culms decumbent, few branched; robust; 200-350 cm long; 1 cm thick; spongy; rooting from lower nodes. Culm internodes solid. Culm nodes glabrous. Leaf-sheaths glabrous or with hairs on upper surface, outer margin glabrous or with hairs. Ligule a membrane 1-2.5 mm long, or absent. Leaf-blade base lobed and clasping. Leaf-blades flat, lanceolate or linear-triangular; 15-40 cm long; 12-30(60) mm wide. Leaf-blade surface glabrous. Leaf-blade margins scabrous; tuberculate-ciliate; basal margins long-ciliate. Leaf-blade apex acuminate gradually narrowed from the base. Inflorescence a spike-like panicle. Panicle densely flowered; cylindrical; 10-40 cm long; 1-3 cm wide. The lower branches often distant; erect.",
    "habitat": "a semi-aquatic perennial grass that forms dense infestations in freshwater systems. It is also quite common in sugar-growing areas, where it is occasionally known to invade plantations. ",
    "controlMethods": "Mechanical control: manual weeding or grazing for livestock. Chemical control: Application of pre-sowing herbicide e.g. glyphosate+ imazapyr",
    "herbicideResistance": "",
    "reference": "http://www.cabi.org/isc/datasheet/109219 https://keyserver.lucidcentral.org/weeds/data/media/Html/hymenachne_amplexicaulis.htm",
    "imageCopyright": "",
    "images": { seed: require('../images/plant-images/Hymenachne_amplexicaulis/Hymenachne_amplexicaulis_seed_1.JPG'), mature: require('../images/plant-images/Hymenachne_amplexicaulis/Hymenachne_amplexicaulis_mature_1.JPG')}
  },
  {
    "identifier": "41",
    "scientificName": "Pennisetum pedicellatum",
    "seedType": "oblong, ovoid",
    "plantType": "Grass",
    "lowland": "✔",
    "upland": "",
    "commonName": "Deenanath grass",
    "khmerName": "",
    "familyName": "Poaceae",
    "description": "Annual tufted grass, rarely perennial in subsp. unispiculum. Grass culms are herbaceous; reaching a height of 30-150 cm; leaves hairy, 5-25 cm long and 4-15 mm wide, arranged in two rows. Inflorescence is a tight panicle, cylindrical, 5-15 cm long and 10-15 mm wide; inflorescence exerted from uppermost leaf-sheath; rachis angular, puberulous, and very rarely pubescent; branches ending in bristle-like appendages. Upper glume and lower lemma more or less 3-lobed, 2.5-6 mm long; upper lemma obtuse, thinly coriaceous, ciliolate at the apex, readily disarticulating from the rest of the spikelet. Spikelets 4-6 mm long solitary, falling entire at maturity with bristles. Spikelets in clusters of 1-5 within the involucre, at least one of the spikelets upon a pedicel 1-3 mm long; bristles densely woolly plumose, forming a fluffy ovate involucre 0.5-1 cm long. 2-flowered, lower floret of fertile spikelet male, upper bisexual or female, bisexual mixed in the same inflorescence, lower glume shorter than florets, completely surrounded by a ring of bristles. Bristles free to base, fine and thread-like. Involucre bristles hairy, rhachis glabrous, spikelets pedicelled within involucre",
    "habitat": "A common agricultural weed, present on cultivated fields, also managed grasslands as well as extensively grazed savannahs. It is a weed in tropical uplands and croplands following disturbance or forest clearing, but is less common within forests and plantations, performing poorly under dense shade. It can also found on cultivated and pasture lands ",
    "controlMethods": "Mechanical control: manual weeding on seedlings. Chemical control: pre-sowing herbicide e.g. glyphosate",
    "herbicideResistance": "",
    "reference": "http://www.cabi.org/isc/datasheet/39769",
    "imageCopyright": "",
    "images": { seed: require('../images/plant-images/Pennisetum_pedicellatum/Pennisetum_pedicellatum_seed_1.JPG'), mature: require('../images/plant-images/Pennisetum_pedicellatum/Pennisetum_pedicellatum_mature_1.JPG'), flower: require('../images/plant-images/Pennisetum_pedicellatum/Pennisetum_pedicellatum_flower_1.JPG')}
  },
  {
    "identifier": "42",
    "scientificName": "Sporobolus diander",
    "seedType": "oblong, ovoid",
    "plantType": "Grass",
    "lowland": "✔",
    "upland": "",
    "commonName": "Tussock dropseed",
    "khmerName": "",
    "familyName": "Poaceae",
    "description": "Tufted perennial without rhizomes; culms 15-75 cm high, erect or geniculately ascending. Leaf-blades nearly always involute, up to 30 cm long, occasionally flat and then up to 4 mm wide. Panicle pyramidal or narrowly lanceolate, loose, up to 20 cm long, the primary branches erect or somewhat spreading, 1.5-5 cm long, bare at the base. Spikelets 1.2-1.6 mm long; glumes lanceolate to ovate-lanceolate, shorter than the spikelet, obtuse, the lower 03-0.5 mm long, the upper 0.6-0.9 mm long; lemma narrowly ovate, as long as the spikelet, acute; anthers 2, sometimes 3, 0.3-0.4 mm long. Grain oblong or elliptic-oblong, 0.6-0.8 mm long, truncate at the tip",
    "habitat": "",
    "controlMethods": "",
    "herbicideResistance": "",
    "reference": "http://www.efloras.org/florataxon.aspx?flora_id=5&taxon_id=200026355",
    "imageCopyright": "",
    "images": { seed: require('../images/plant-images/Sporobolus_diander/Sporobolus_diander_seed_1.JPG'), mature: require('../images/plant-images/Sporobolus_diander/Sporobolus_diander_mature_2.JPG')}
  },
  {
    "identifier": "43",
    "scientificName": "Corchorus aestuans",
    "seedType": "cuneate",
    "plantType": "Broadleaf",
    "lowland": "✔",
    "upland": "✔",
    "commonName": "",
    "khmerName": "",
    "familyName": "Teliaceae",
    "description": "Herbs annual, to 1 m tall. Stem red-brown, slightly yellowish puberulent; branches slender. Petiole 0.9-1.6 cm, with yellowish, long, rigid hairs; leaf blade ovate or broadly ovate, 4.5-6.5 × 3-4 cm, sparsely pilose on both surfaces, glabrescent, basal veins 5-7, lateral veins 3-6 pairs, base rounded, margin serrate, basal pair of teeth usually elongating into filiform or caudate appendages, apex shortly acuminate or acute. Flowers solitary or several together in cymes, axillary or leaf-opposed; peduncle and pedicel very short or absent. Sepals 5, purple-red abaxially, narrowly oblong, ca. 5 mm, semi-foveolately boat-shaped distally, apex awned. Petals 5, yellow, nearly as long as sepals, obovate. Stamens many, yellow, ca. 3 mm. Ovary 3-5-loculed, long cylindrical, puberulent; style rodlike; stigma beaklike, 5-toothed. Capsule cylindrical, angled, 3-5-valved, 1.2-2.5 × ca. 0.5 cm, apex 3-5-angled, awns bifurcate. Seeds separated by transverse septum.",
    "habitat": "A weed of waste ground from sea level to 2,000 metres. Grassy savannah, fallow land; sandy riverbeds; small alluvial depressions; on heavy alluvial soils; in clay near granitic outcrops at elevations up to 1,350 metres.",
    "controlMethods": "",
    "herbicideResistance": "http://tropical.theferns.info/viewtropical.php?id=Corchorus+aestuans http://www.efloras.org/florataxon.aspx?flora_id=2&taxon_id=200013573",
    "reference": "",
    "imageCopyright": "",
    "images": { seed: require('../images/plant-images/Corchorus_aestuans/Corchorus_aestuans_seed_1.JPG'), mature: require('../images/plant-images/Corchorus_aestuans/Corchorus_aestuans_mature_1.JPG'), flower: require('../images/plant-images/Corchorus_aestuans/Corchorus_aestuans_flower_1.JPG')}
  },
  {
    "identifier": "44",
    "scientificName": "Xyris indica",
    "seedType": "elliptic",
    "plantType": "Grass",
    "lowland": "✔",
    "upland": "",
    "commonName": "Yellow-eyed grass",
    "khmerName": "",
    "familyName": "Xyridaceae",
    "description": "Herbs perennial, robust. Leaf sheath 7--20(--25) cm; leaf blade ensiform-linear, 15--60 cm × 4--8 mm, glabrous, veins indistinct when dry, connected by numerous, prominent, transverse ribs, apex acute to obtuse. Peduncle 15--65 cm, veins prominent. Spikes ovoid, oblong-ovoid, or ellipsoid, 1.2--3.5 × 1--1.5 cm; bracts yellowish brown, suborbicular, obovate, or conchiform, 5--8 × 5--7 mm, minutely papillose on apical 1/3, base obtuse to truncate, margin gold-colored, membranous, apex entire or emarginate. Lateral sepals linear-spatulate, 5--7 × 0.8--1.4 mm, keel denticulate, apex obtuse; median sepal hooded, 4--6 × 2--2.5 mm, 1-veined. Petals yellowish to yellow; limb obovate to suborbicular, 3--4.5 × 3--4 mm, margin serrulate; claw 3.5--5 × ca. 0.5 mm. Stamens ca. 4 mm; anthers ovate, apex broadly incised, with a short mucro in incision. Staminodes 2--3 mm. Ovary obovoid, 1-loculed. Capsule globose to obovoid, 3--4 mm. Seeds ovoid, ca. 0.5 mm. ",
    "habitat": "grows in swamps, moist localities, streams, pools, ponds, rice fields",
    "controlMethods": "",
    "herbicideResistance": "",
    "reference": "http://idtools.org/id/appw/factsheet.php?name=13084 http://www.efloras.org/florataxon.aspx?flora_id=2&taxon_id=200027359 http://www.iucnredlist.org/details/194171/0",
    "imageCopyright": "",
    "images": { seed: require('../images/plant-images/Xyris_indica/Xyris_indica_seed_1.JPG'), mature: require('../images/plant-images/Xyris_indica/Xyris_indica_mature_1.JPG'), flower: require('../images/plant-images/Xyris_indica/Xyris_indica_flower_1.JPG')}
  }
]
